version: "3.4"

services:
  app:
    container_name: react-native
    command: npm start
    restart: always
    # env_file:
    #   - ./.env
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - ./:/source/
