name: Deploy to app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      # - name: Build Android App Bundle
      #   run: |
      #     cd android && ./gradlew bundleRelease --no-daemon

      - name: Build Android App Apk
        run: |
          cd android
          ./gradlew assembleRelease

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test.aab
      #     path: "android/app/build/outputs/bundle/release/app-release.aab"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ github.run_number }}.apk
          path: "android/app/build/outputs/apk/release/app-release.apk"

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: test.aab
      #     path: "android/"

      - uses: actions/download-artifact@v3
        with:
          name: test-${{ github.run_number }}.apk
          path: "android/MkAUGaN1b/"

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          # AWS_REGION: ${{ secrets.AWS_REGION }}
          source_dir: 'android/MkAUGaN1b/test-${{ github.run_number }}.apk'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      # - name: Upload artifact to App Center
      #   uses: wzieba/AppCenter-Github-Action@v1
      #   with:
      #     appName: test.com/test-Android
      #     token: ${{secrets.APP_CENTER_TOKEN_ANDROID}}
      #     group: UKInternal
      #     file: android/app-release.aab
      #     notifyTesters: true
      #     debug: false